name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Verificar archivos
        run: |
          if [ -f index.html ] && [ -f styles.css ]; then
            echo "Archivos encontrados ✔"
          else
            echo "Faltan archivos ❌"
            exit 1
          fi

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Simular despliegue
        run: echo "Artefactos listos para el despliegue en Staging 🚀"